# Generated by Django 5.0.7 on 2026-02-15 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, default='PRODUCT', max_length=32)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attendees.dataupload')),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('upload', 'email'), name='uniq_attendee_per_upload'),
        ),
    ]
